use_frameworks!

platform :ios, '10.0'

pod 'Alamofire',  '~> 5.10.2'

target 'DebugCenter_Example' do
  pod 'DebugCenter', :path => '../'

  target 'DebugCenter_Tests' do
    inherit! :search_paths

    
  end
end
